name = "jqx"
license = "MIT"
licenselink = "https://raw.githubusercontent.com/xtod/hugo-jqx/refs/heads/main/LICENSE"
description = "Hugo blog theme as simple as paper"
homepage = "https://github.com/xtod/hugo-jqx"
demosite = "https://0x8.net"
tags = ["responsive", "clean", "blog", "simple", "minimal", "mobile"]
features = []
min_version = "0.158.0"

[author]
  name = "jqx"
  homepage = "https://jqx.me/"
