name = "essay"
license = "MIT"
licenselink = "https://raw.githubusercontent.com/xtod/hugo-essay/refs/heads/main/LICENSE"
description = "a simple hugo theme as paper"
homepage = "https://github.com/xtod/hugo-essay"
demosite = "https://0x8.net"
tags = ["responsive", "clean", "blog", "simple", "minimal", "mobile"]
features = ["clean","minimal", "mobile"]
min_version = "0.160.0"

[author]
  name = "jqx"
  homepage = "https://jqx.me/"
